### PR TITLE
fix(serverless-api): use new /Status endpoint for builds

### LINKED ISSUE #193: Migrate to build /Status endpoint whenever polling for build status
The Serverless API now has a new /Status endpoint, which can be used to poll for the build status (instead of getting the same information from the build instance endpoint). You can make a request to `.../v1/Services/ZSxxx/Builds/ZBxxx/Status` in order to retrieve the build status. The status will still be one of building, completed, or failed. A sample response is: 
```
{
  "status": "completed",
  "url": "https://serverless.twilio.com/v1/Services/ZS55426da69ac03846ec3b1e91686e9c44/Builds/ZB0635857af9586779efb77fe6c613e2d0/Status",
  "account_sid": "AC1d740955285dfa48d491cde240fc58d0",
  "service_sid": "ZS55426da69ac03846ec3b1e91686e9c44",
  "sid": "ZB0635857af9586779efb77fe6c613e2d0"
}
```

The key in question is still `status`, but the response should be much faster than using the builds instance endpoint. :)

### PR DESCRIPTION
**Pull request by dkundel**
There is a "new" dedicated `/Status` endpoint for Builds that is designed to be long polled. 

fix #193 

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

File: packages/serverless-api/src/api/builds.ts [hunk 1]
```diff
@@ -42,14 +48,18 @@ export async function getBuild(
...
   client: TwilioServerlessApiClient
 ): Promise<BuildStatus> {
   try {
-    const resp = await getBuild(buildSid, serviceSid, client);
-    return resp.status;
+    const resp = await client.request(
+      'get',
+      `Services/${serviceSid}/Builds/${buildSid}/Status`
+    );
+    // const resp = await getBuild(buildSid, serviceSid, client);
```
Comment (philnash) [inline packages/serverless-api/src/api/builds.ts]: Comment got left behind here.

**Review by philnash — APPROVED** [review]
:+1:
