### PR TITLE
fix(plugin-serverless): handle direct username/password input

### LINKED ISSUE #261: Deployment with --username and --password as API Key/Secret fails
If you deploy with --username and --password as API Key and API Secret it fails with a 404 where it grabs the wrong Service SID and tries to access /Environments.

regarding #255

### PR DESCRIPTION
**Pull request by dkundel**
Previously if you'd call `twilio serverless:deploy` or similar commands with `--username` and
`--password` explicitly passed as API Key/Secret, it would both read the Service SID and write the
Service SID in the deployinfo cache for the Account SID that was associated with the default
profile. This change will ignore the default profile/client if username or password are passed.

BREAKING CHANGE: You have to use --username and --password effectively together if you use either

fix #261

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

File: packages/plugin-serverless/src/utils.js [hunk 1]
```diff
@@ -69,6 +69,17 @@ function normalizeFlags(flags, aliasMap) {
 function createExternalCliOptions(flags, twilioClient) {
   const profile = flags.profile;
 
+  if (flags.username || flags.password) {
+    return {
+      username: flags.username,
```
Comment (ktalebian) [inline packages/plugin-serverless/src/utils.js:77]: Doesn't this mean `username` or `password` could potentially be null here? Is that okay?

**Review by ktalebian — APPROVED** [review]

File: packages/plugin-serverless/src/utils.js (hunk 1 above)
Comment (dkundel) [reply packages/plugin-serverless/src/utils.js:77]: Realistically they wouldn't but I wrote a more proper check

**Review by ktalebian — APPROVED** [review]
